# More configuration examples: https://github.com/jakubknejzlik/admin-as-service/blob/master/example/config.yml
title: Administrace uživatelů
basePath: '/admin/'
url: ..
auth:
  grantType: password
  authorizeUrl: ${AUTH_URL}/auth/token
  clientId: default_client
  clientSecret: 123456
  scope: accounts
entities:
  users:
    name: Users
    list:
      fields:
        - attribute: username
          label: Username
          type: string
          main: true
        - attribute: firstname
          label: Firtname
          type: string
        - attribute: lastname
          label: Lastname
          type: string
        - attribute: roles_id
          label: Role
          type: reference
          toMany: true
          entity: roles
          targetField: name 
    fieldsets:
      - title: Basic info
        fields:
        - attribute: username
          label: Username
          type: email
          required: true
        - attribute: password
          label: Password [sha512 hash]
          type: string
          required: true
        - attribute: firstname
          label: Firstname
          type: string
        - attribute: lastname
          label: Lastname
          type: string
      - title: Access control
        fields:
        - attribute: roles_id
          label: Role
          type: reference
          toMany: true
          entity: roles
          targetField: name 
        - attribute: permissions
          label: Permissions
          type: text
      - title: Additional informations
        fields:
        - attribute: metadata
          label: Metadata (YAML)
          type: text
  roles:
    name: Role
    list:
      fields:
        - attribute: name
          label: Name
          main: true
    fields:
      - attribute: name
        label: Name
        type: string
        required: true
      - attribute: permissions
        label: Permissions
        type: text
  clients:
    name: OAuth clients
    list:
      fields:
        - attribute: name
          label: Name
          main: true
        - attribute: uid
          label: Client ID
          main: true
        - attribute: grants
          label: OAuth grant types
          type: string
    fields:
      - attribute: name
        label: Name
        type: string
        required: true
      - attribute: grants
        label: OAuth grant types
        type: string
      - attribute: uid
        label: Client ID
        type: string
      - attribute: secret
        label: Secret
        type: string